
opensoft_rollout:
    path: /
    defaults:
        _controller: Opensoft\RolloutBundle\Controller\DefaultController::indexAction

opensoft_rollout_feature_activate:
    path: /{feature}/activate
    defaults:
        _controller: Opensoft\RolloutBundle\Controller\DefaultController::activateAction

opensoft_rollout_feature_deactivate:
    path: /{feature}/deactivate
    defaults:
        _controller: Opensoft\RolloutBundle\Controller\DefaultController::deactivateAction

opensoft_rollout_feature_increment_percentage:
    path: /{feature}/increment-percentage
    defaults:
        _controller: Opensoft\RolloutBundle\Controller\DefaultController::incrementPercentageAction

opensoft_rollout_feature_decrement_percentage:
    path: /{feature}/decrement-percentage
    defaults:
        _controller: Opensoft\RolloutBundle\Controller\DefaultController::decrementPercentageAction

opensoft_rollout_feature_activate_group:
    path: /{feature}/activate-group/{group}
    defaults:
        _controller: Opensoft\RolloutBundle\Controller\DefaultController::activateGroupAction

opensoft_rollout_feature_deactivate_group:
    path: /{feature}/deactivate-group/{group}
    defaults:
        _controller: Opensoft\RolloutBundle\Controller\DefaultController::deactivateGroupAction

opensoft_rollout_feature_activate_user:
    path: /{feature}/activate-user
    defaults:
        _controller: Opensoft\RolloutBundle\Controller\DefaultController::activateUserAction

opensoft_rollout_feature_deactivate_user:
    path: /{feature}/deactivate-user/{id}
    defaults:
        _controller: Opensoft\RolloutBundle\Controller\DefaultController::deactivateUserAction

opensoft_rollout_feature_remove:
    path: /{feature}/remove
    defaults:
        _controller: Opensoft\RolloutBundle\Controller\DefaultController::removeAction

opensoft_rollout_feature_set_request_param:
    path: /{feature}/set-request-param
    defaults:
        _controller: Opensoft\RolloutBundle\Controller\DefaultController::setRequestParamAction
